### ISSUE TITLE
steamからgameの起動を検知する方法

### ISSUE THREAD

**Issue by cake-fuka** [cake-fuka/steam-buddy-go#1]
https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=xxx&steamids=xxx
を叩くとgameをplay中であれば下記のようなレスポンスが変える
```
{
  "response": {
    "players": [
      {
...
        "gameextrainfo": "Skul: The Hero Slayer",
        "gameid": "1147560",
...
      }
    ]
  }
}
```

そこでticker的なもので数十秒ごとにこのAPIを叩いて、以下のようにSlack通知を出す
* game開始
   * Slack通知
   * play中のgameidを格納しておく
* game play中
   * gameidが同じ場合には何もしない
   * gameidが変わっている場合には別のgameが開始しているので、終了通知 + 新しいgame通知
* game終了
   * gameidがなくなるのでgame終了通知
   * tickerの時間より早くgameが切り替わる場合にはgameidが変更されているか

**Comment by cake-fuka** [comment]
APをたたくためには、steamのAPI keyとsteam idが必要
これらをとってくるには
[API key](https://steamcommunity.com/dev/apikey)
[steam id](https://store.steampowered.com/account/)

とりあえず環境変数に差し込んで起動するようにする

**Comment by hfukasaw** [comment]
こちらで機能追加完了
https://github.com/cake-fuka/steam-buddy-go/commit/1f60c570ffeeb7347f5f78b050237978f60102e7
